# Content Types, Goals, and Metrics Configuration
content_types:
  - text
  - carousel
  - poll
  - newsletter
  - video_script
  - document

content_goals:
  - thought_leadership
  - engagement
  - lead_generation
  - brand_awareness
  - recruitment

optimization_metrics:
  - engagement_rate
  - click_through
  - conversion_rate
  - follower_growth
  - reach

# Brand Voice Configuration
brand_voice:
  tone:
    - casual
    - empathetic
    - reflective
    - experience-based
  style:
    - conversational
    - storytelling
    - educational
    - problem-solving
  personality:
    - authentic
    - vulnerable
    - curious
    - trustworthy
    - helpful
  key_phrases:
    - real-world implementation
    - practical insights
    - team learnings
    - industry challenges
    - continuous improvement
    - collaborative innovation
  emoji_style: minimal
  industry_hashtags:
    - AIJourney
    - TechLessons
    - InnovationStories
    - BuildingInPublic
    - TechExperiences
    - FutureOfWork

# Content Configuration
content_config:
  primary_goal: thought_leadership
  target_audience:
    - tech executives
    - startup founders
    - innovation leaders
    - IT decision makers
  industry_context: AI and Machine Learning
  custom_parameters:
    content_length: medium
    include_statistics: true
    hashtag_style: integrated
    carousel_slides: 6
    poll_options: 4
    video_length_minutes: 3

# Templates
templates:
  hooks:
    text:
      - "Last week, I encountered an interesting challenge with {topic}..."
      - "Here's what surprised me after implementing {topic}..."
      - "A team member's question about {topic} made me realize..."
      - "After months of hands-on experience with {topic}, I've noticed..."
      - "Let me share a recent {topic} implementation story..."
    carousel:
      - "Lessons learned from our {topic} journey"
      - "Real challenges we faced with {topic}"
      - "What nobody tells you about {topic}"
      - "{topic}: From Theory to Practice"
      - "Our team's approach to {topic}"
    poll:
      - "What's your biggest challenge with {topic}?"
      - "How is your team approaching {topic}?"
      - "What's your experience with {topic}?"
      - "Which {topic} challenge resonates most?"
    newsletter:
      - "Real-world {topic} Insights"
      - "This Week in {topic}: Field Notes"
      - "Practical {topic} Lessons"
      - "{topic}: Stories from the Trenches"
    video_script:
      - "Lessons from implementing {topic}"
      - "Real-world {topic} stories"
      - "Behind the scenes: {topic} in action"
    document:
      - "Practical Guide: {topic} Implementation"
      - "Field Notes: {topic} in Practice"
      - "Team Learnings: {topic} Journey"

  cta:
    engagement:
      - "What challenges have you faced with {topic}? Would love to hear your story"
      - "Has your experience been different? Let's discuss"
      - "Curious to hear your perspective on this"
      - "What's been your biggest learning in this space?"
    lead_generation:
      - "Happy to share more about our learning process"
      - "We're hosting a discussion on {topic} challenges next week"
      - "I've documented our journey - DM if you'd like to learn more"
      - "Let's connect and share experiences"
    thought_leadership:
      - "What unexpected challenges have you encountered?"
      - "How has your approach to {topic} evolved?"
      - "What's been your most valuable lesson?"
    brand_awareness:
      - "More stories from our {topic} journey coming soon"
      - "Here's how we're learning and growing with {topic}"
      - "Join us in exploring {topic} challenges"
    recruitment:
      - "Want to solve {topic} challenges together?"
      - "Looking for curious minds to explore {topic}"
      - "Join our learning journey with {topic}"

  carousel_sections:
    - Introduction and Problem Statement
    - Current Industry Challenges
    - Solution Overview
    - Key Benefits
    - Implementation Steps
    - Best Practices
    - Common Pitfalls
    - Success Metrics
    - Case Studies
    - Resources and Next Steps

  poll_structures:
    implementation:
      - "Already implemented"
      - "Planning to implement"
      - "Considering it"
      - "Not interested"
    preference:
      - "Option A: {choice_a}"
      - "Option B: {choice_b}"
      - "Option C: {choice_c}"
      - "Other (comment below)"
    timeline:
      - "< 3 months"
      - "3-6 months"
      - "6-12 months"
      - "> 12 months"

  newsletter_sections:
    - "🔥 Top Stories"
    - "📊 Industry Updates"
    - "💡 Expert Insights"
    - "🎯 Best Practices"
    - "📚 Resources"
    - "📅 Upcoming Events"

  video_script_sections:
    - "Hook (0:00-0:15)"
    - "Introduction (0:15-0:45)"
    - "Main Points (0:45-2:15)"
    - "Examples/Case Studies (2:15-2:45)"
    - "Conclusion & CTA (2:45-3:00)"

  document_sections:
    whitepaper:
      - "Executive Summary"
      - "Industry Overview"
      - "Challenge Analysis"
      - "Solution Framework"
      - "Implementation Guide"
      - "ROI Analysis"
      - "Conclusions"
    case_study:
      - "Client Background"
      - "Challenge"
      - "Solution"
      - "Implementation"
      - "Results"
      - "Lessons Learned"

# Content Formatting
formatting:
  text:
    max_paragraphs: 6
    lines_per_paragraph: 3
    emoji_density: low
  carousel:
    slides_per_post: 8-10
    points_per_slide: 3-4
    image_text_ratio: 60-40
  video:
    ideal_duration: 2-3min
    section_breakdown:
      intro: 15%
      content: 70%
      conclusion: 15%
  document:
    page_length: 5-7
    section_distribution:
      intro: 10%
      body: 80%
      conclusion: 10%

# Success Patterns
engagement_patterns:
  high_performing:
    - "Share specific implementation challenges"
    - "Include real team experiences"
    - "Discuss both successes and failures"
    - "Ask about others' experiences"
  best_practices:
    - "Write conversationally"
    - "Share context and background"
    - "Include specific examples"
    - "End with genuine questions"